spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  redis:
    # 数据库索引
    database: 0
    # Redis 服务器地址
    host: localhost
    # Redis 服务器端口
    port: 6379
    password:
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: myproject
server:
  servlet:
    session:
      timeout: 3600
  port: 8080