server:
  port: 8081

dubbo:
  application:
    # 服务名称, 保持唯一
    name: server-consumer
    # 监控和管理功能, 默认端口 22222
    qos-port: 33333
  # zookeeper地址, 用于从中获取注册的服务
  registry:
    address: zookeeper://localhost:2181
  protocol:
    # dubbo协议, 固定写法
    name: dubbo
    port: -1
