spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    # 指定为 HikariDataSource
    type: com.zaxxer.hikari.HikariDataSource
    # hikari 连接池配置 对应 HikariConfig 配置属性类
    hikari:
      # 表示连接池的用户定义名称，主要出现在日志记录和 JMX 管理控制台中，用于标识池和池配置。
      # 自动生成
      pool-name: HikariCP-First
      # 此属性控制从池返回的连接的默认自动提交行为。它是一个布尔值
      # 默认值：true
      auto-commit: true
      # 此属性控制客户端（即您）等待来自池的连接的最大毫秒数。如果超过此时间而没有可用连接，则会抛出 SQLException。可接受的最低连接超时为 250 毫秒
      # 默认值：30000（30 秒）
      connection-timeout: 30000
      # 空闲连接存活最大时间，值 0 表示永远不会从池中删除空闲连接。允许的最小值为 10000 毫秒（10 秒）
      # 默认值：600000（10 分钟）
      idle-timeout: 600000
      # 此属性控制 HikariCP 尝试保持连接活动的频率，以防止数据库或网络基础设施超时。该值必须小于该 maxLifetime值。允许的最小值为 30000 毫秒（30 秒）
      # 默认值：0（禁用）
      keepalive-time: 0
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，允许的最小值为 30000 毫秒（30 秒）
      # 默认值：1800000（30 分钟）
      max-lifetime: 1800000
      # 最小空闲数
      # 默认值：10
      minimum-idle: 5
      # 连接池最大连接数
      # 默认值：10
      maximum-pool-size: 10
      # 连接测试 query，如果驱动程序支持 JDBC4，强烈建议不要设置此属性。
      connection-test-query: SELECT 1